# Generated by Django 3.2.5 on 2022-02-18 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
